
exclude:
  languages

mapping:
  "David Molineus <david.molineus@netzmacht.de>":
    - "David Molineus <mail@netzmacht.de>"
  "Christopher Boelter <christopher@boelter.eu>":
    - "cboelter <christopher@boelter.eu>"